[build]
  command = "npm run netlify-build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16.20.2"
  NPM_VERSION = "8.19.4"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
