[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.13.1"
  NPM_VERSION = "10.7.0"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.processing]
  skip_processing = false
  compress = true
