[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_VERSION = "10.9.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  target = "es2020"

[functions]
  node_bundler = "esbuild"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  skip_processing = false
  pretty_urls = true

[build.processing.images]
  compress = true
